baseURL = "https://rk1165.github.io/"
languageCode = "en-us"
title = "Ravi Kumar's website"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
pagination.pagerSize = 10
enableEmoji = true

[params]
  author = "Ravi Kumar"
  description = "My Musings on various things"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  since = 2024
  colorScheme = "auto"
  enableTwemoji = true
  hidecolorschemetoggle = false

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  author = "authors"

[[params.social]]
  name = "GitHub"
  icon  = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/rk1165/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/ravi-kumar-713057249/"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 3
  url = "https://rk1165.github.io/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[markup.highlight]
style = "github-dark"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"

[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"

[[menu.main]]
  name = "Notes"
  weight = 4
  url = "notes/"

